:stem: asciimath


= Podstawy technologii blockchain i przykłady jej wykorzystania przez IBM

Blockchain jest rozproszoną bazą danych, gdzie każda kolejna porcja informacji, zwana blokiem, jest nierozerwalnie powiązana z poprzednią, tworząc tytułowy łańcuch bloków. Bezpieczeństwo i zaufanie treści wraz z więzami w blockchainie jest wdrożone z użyciem mechanizmów kryptograficznych. Najczęściej ta technologia służy za rozproszoną księgę rachunkową (z ang. DLT - distributed ledger technology) w kryptowalutach (np. w Bitcoinie), gdzie umożliwia ona przeprowadzanie transakcji z pominięciem zaufanej trzeciej strony (głównie banków).

W celu dokładniejszego przyjrzenia się najważniejszym elementom, które składają się na blockchain w wersji Bitcoina opublikowanej w 2008 r. przez anonimowego Satoshiego Nakamoto, posłużę się wyimaginowaną historyjką. Wyobraźmy sobie, że troje przyjaciół: szlachetny latarnik, bystra syrenka i wiarołomny pirat organizują regularne spotkania towarzyskie. Kupują napoje i przekąski, aby razem biwakować na pobliskiej plaży. Nie przeszkadza im to, że nie za każdym razem koszty rozkładają się po równo. Pirat zaproponował, aby do czasu wyrównania wzajemnych należności zapisywać wszystkie dokonane zakupy na wyrwanej przez niego kartce z zeszytu.

Syrenka zastanawiała się, jak zapewnić uczciwość takiego rejestru, gdyż obawiała się, że pirat zacznie tworzyć fałszywe wpisy, aby wyłudzić pieniądze od pozostałych. Brała pod uwagę podpisywanie każdej transakcji, jednak nie powstrzymałoby to pirata przed podrabianiem podpisów. Latarnik zareagował na przedstawione zagrożenie wysunięciem propozycji, aby listę transakcji przechowywać na komputerze i każdą z nich podpisywać elektronicznie. Takie podpisy bowiem są odporne na próby ich podrobienia.

Bezpieczeństwo podpisów elektronicznych opiera się na zastosowanej kryptografii asymetrycznej. Ich użytkownik posiada 2 klucze: publiczny i prywatny. Informację zaszyfrowaną jednym kluczem można odszyfrować tylko za pomocą drugiego z pary, gdyż jedyny znany sposób złamania tego mechanizmu wymagałby użycia iście astronomicznych mocy obliczeniowych (nie wspominam tutaj o potencjalnym wykorzystaniu komputerów kwantowych). Nadawca wiadomości może bezpiecznie ją zaszyfrować, używając klucza publicznego odbiorcy, aby wyłącznie on mógł ją rozszyfrować swoim kluczem prywatnym po jej otrzymaniu. Nadawca może dodatkowo zaszyfrować wysyłaną treść także swoim kluczem prywatnym, aby odbiorca był w stanie potwierdzić jego tożsamość poprzez skuteczne odszyfrowanie wiadomości kluczem publicznym nadawcy. Ten ostatni schemat stanowi podstawę działania podpisu elektronicznego. Na marginesie warto dodać, że niestety w rzeczywistości kwestia zachowania poufności i integralności poczty elektronicznej jest nieporównywalnie bardziej złożona, ale nie będę zgłębiał tego tematu w tym artykule.
Syrenka zauważyła drobne niedociągnięcie w pomyśle latarnika. Otóż, wciąż można było duplikować transakcje już po elektronicznym ich podpisaniu. Zakładając, że syrenka podpisała wysłanie pewnej kwoty piratowi, mógł on następnie skopiować cały ten wpis, aby ukraść jej pieniądze. Okazało się, że usunięcie tej niedoskonałości wymaga tylko unikalnego numerowania transakcji. Jeśli transakcja zawiera niepowtarzalny identyfikator, a następnie zostaje podpisana, to duplikat takiego wpisu nie zostanie uznany.

Latarnika natomiast zaniepokoił inny scenariusz. Nie był przekonany, że pirat zechce wywiązać się ze swoich zobowiązań finansowych w przyszłości. Nakazał zatem, aby na początku rejestru dodać 3 transakcje, w których każdy ze znajomych otrzymałby pewne wirtualne środki. W blockchainie Bitcoina można utożsamiać to z treścią pierwszego bloku, czyli tzw. bloku “Genesis”. W ten sposób latarnik wymusiłby na wszystkich, aby nie wydawali więcej niż wynosi ich aktualne saldo. Pirat przyjął to postanowienie ze spokojem, gdyż wprowadzało ono swoistą walutę cyfrową. Nie musiał więc już nigdy przekazywać pieniędzy w obowiązującej walucie (np. w złotych), dopóki w rejestrze posiadał jakieś środki.

Do ustalenia pozostała kwestia administratora serwera, na którym znajduje się rejestr transakcji. Latarnik wydawał się bezspornym kandydatem. Pirat jednak, oburzony zignorowaniem jego osoby i ciągłą podejrzliwością swoich pobratymców, sprzeciwił się aspiracjom latarnika. Błyskotliwa syrenka wpadła w tym momencie na pomysł, jak osiągnąć kompromis w narastającym konflikcie. Wszyscy znajomi mają przechowywać kopię rejestru i demokratycznie ustalać, jaka jest jego prawdziwa wersja w danym momencie. Pirat zwęszył w tym okazję, gdyż mógł stworzyć wiele kont i manipulować wynikami głosowania, sztucznie zwielokrotniając siłę swojego głosu. W informatyce w takich okolicznościach pojawia się problem podwójnego wydawania tych samych środków (z ang. double-spending problem). Zdający sobie z tego sprawę latarnik zaproponował alternatywne rozwiązanie. Postawił na dowód wykonania pracy (z ang. proof of work), czyli w uproszczeniu na głosowanie dostępną mocą obliczeniową. Wtedy niezależnie od ilości utworzonych kont skala wykonanej pracy pozostaje stała, gdyż jest ona zależna wyłącznie od mocy posiadanego sprzętu. Przynajmniej początkowo wolno założyć, że każdy dysponuje podobnym komputerem, więc będzie miał zbliżony wpływ na ustalenie wspólnej wersji rejestru. Późniejsze dokupienie dedykowanych zasobów zasadniczo nie psuje wspomnianego mechanizmu, o ile nikt nie włada większością mocy obliczeniowej (z ang. 51% attack).

Ściślej rzecz ujmując, dowód pracy w sieci blockchain przeprowadza się w następujący sposób. Grupujemy niepotwierdzone jeszcze transakcje (ale podpisane już elektronicznie) w jeden blok. Następnie haszujemy te wszystkie transakcje (szczegóły w następnym akapicie), otrzymując jeden hasz (z ang. hash). W literaturze zamiast hasza natrafia się czasem na słowo skrót (z ang. digest), ale nie jest ono w pełni trafione, gdyż funkcja haszująca nie zawsze skraca (hasz odpowiednio krótkiego napisu będzie dłuższy od niego samego). Potem bierzemy hasz poprzedniego bloku, tworząc trwałe połączenie między nowo tworzonym blokiem a tym bezpośrednio wcześniejszym. Używamy także przybliżonego czasu powstania bloku (z ang. timestamp - znacznik czasu) i z góry ustalonej liczby celu (z ang. target). Wymienione właśnie 4 składniki: hasz transakcji, hasz poprzedniego bloku, znacznik czasu i liczba celu tworzą nagłówek bloku (z ang. block header). Ostatecznie do nagłówka dodajemy jeszcze tzw. liczbę nonce (skrót z ang. number used only once - liczba użyta tylko raz) taką, aby hasz całego nagłówka był liczbą mniejszą lub równą celowi. Znalezienie nonce’a spełniającego podany warunek jest bardzo trudne. Hasz produkowany przez funkcję haszującą SHA256 (z ang. Secure Hash Algorithm - Bezpieczny Algorytm Haszujący) może maksymalnie wynosić stem:[2^256-1], co jest liczbą względnie porównywalną z szacunkiem atomów we wszechświecie (ok. stem:[10^80]). Szansa na znalezienie takiego nonce’a, aby hasz nagłówka był odpowiednio małą liczbą, jest zatem bardzo mała. Co więcej, SHA256 jest kryptograficzną funkcją haszującą, więc nie jest znany żaden efektywny sposób na dedukcję nonce’a z hasza. W tej sytuacji nonce jest po prostu zgadywany po ogromnej ilości prób i błędów. Kiedy ostatecznie do tego dojdzie, nowo powstały blok jest rozgłaszany wszystkim uczestnikom w sieci blockchain i dodawany do niego. Może oczywiście dojść w tym momencie do rozwidlenia blockchaina (z ang. fork), gdzie co najmniej dwa konkurencyjne bloki zaczną wskazywać na jeden poprzedni blok. Te rozbieżności niweluje się poprzez uznanie najdłuższej gałęzi łańcucha za tę obowiązującą. Im bowiem jest ona dłuższa, tym większa pewność, że została ona wygenerowana przez największą część dostępnej mocy obliczeniowej. W tym schemacie tkwi siła bezpieczeństwa blockchaina. Skoro przetrwa tylko najsilniejsza odnoga blockchaina, to złośliwy aktor nie jest w stanie jej zbudować. Naturalnie przy założeniu, że nie dysponuje większością mocy obliczeniowej w sieci. Dla zainteresowanych wspomnę, że istnieją również inne mechanizmy ustalania konsensusu takie, jak np. dowód stawki (z ang. proof of stake) znany z zastosowania w blockchainie kryptowaluty Ethereum.

Warto jeszcze przyjrzeć się kwestii haszowania transakcji. Operacja ta jest wykonywana na strukturze danych zwanej drzewem hash, in. drzewem Merkle (z ang. Merkle tree). Powstaje ono poprzez shaszowanie wszystkich pojedynczych transakcji, następnie sparowanie powstałych haszy i shaszowanie każdej z tych par, później znowu sparowanie nowych haszy i shaszowanie każdej z tych nowych par i tak dalej, aż na końcu powstanie tylko jeden hasz zwany korzeniem drzewa Merkle (z ang. Merkle root). Ten korzeń jest właśnie ww. haszem transakcji. Niewątpliwą zaletą drzewa Merkle jest możliwość przyspieszonej weryfikacji, czy dana transakcja została wykonana. W tym celu nie trzeba znać wszystkich transakcji w bloku i ich haszy, leczy tylko jedną gałąź, tj. drogę od danej transakcji do korzenia i porównać, czy hasze znajdujące się na niej są poprawne. W ten sposób wyraźnie oszczędza się moc obliczeniową i przepustowość sieci komunikacyjnej (czyli generalnie internetu).

W opowieści o latarniku, syrence i piracie, kiedy siedzieli oni razem przy ognisku, próbując rozwiązać problem zapłaty za kiełbaski i colę, sami wynaleźli technologię blockchain, odkrywając i łącząc ze sobą kolejne jej elementy. W tej fantastycznej historyjce umyślnie pominąłem charakterystyczne zawiłości blockchaina Bitcoina takie, jak zalecenie jednorazowego używania danego adresu (w przeciwieństwie do numerów kont bankowych), czy kwestia komponowania nowych transakcji z poprzednich UTXO (unspent transaction output - niewydane wyjście transakcji). Są one bowiem charakterystyczne dla infrastruktury Bitcoina, zaś moim celem było skupienie się ogólnie na technologii blockchain.

Źródłem inspiracji do napisania tego artykułu był dla mnie materiał o blockchainie użytkownika “3Blue1Brown” dostępny w serwisie YouTube pod adresem https://youtu.be/bBC-nXj3Ng4. Dla żądnych wiedzy o szczegółach działania blockchaina w Bitcoinie polecam książkę Andreasa M. Antonopoulosa pt. “Bitcoin dla zaawansowanych. Programowanie z użyciem otwartego łańcucha bloków” dostępną w języku angielskim na zasadzie wolnej licencji pod linkiem https://github.com/bitcoinbook/bitcoinbook.

Od czasu artykułu Satoshiego Nakamoto powstało wiele konkurencyjnych infrastruktur blockchainów, choć fundamenty pozostały podobne. Okazało się, że blockchain świetnie się nadaje nie tylko do obsługi transakcji, ale również do przechowywania innych rodzajów danych, gdzie liczy się zapewnienie zaufania do nich. Na koniec pragnę przedstawić przykład zastosowania blockchaina poza rynkiem kryptowalut przez firmę IBM. Posiadają oni rozległą wiedzę i wybitne doświadczenie nabyte przy rozwoju i wsparciu frameworka “Hyperledger Fabric” służącego do budowy aplikacji opartych o rozproszone rejestry (DLT). Koncern IBM jest naturalnym wyborem, jeśli chodzi o przedstawienie wzorca wdrożenia technologii blockchain. IBM we współpracy z marką Renault i innymi przedstawicielami przemysłu motoryzacyjnego stworzyło projekt blockchainowy o nazwie XCEED. Służy on do śledzenia i certyfikacji wszelkich części samochodowych w ramach całego cyklu produkcyjnego i sprzedażowego. Jest to szczególnie istotne w środowisku dynamicznie zmieniających się regulacji, do których producenci muszą się niezwłocznie dostosowywać. W stworzonym ekosystemie XCEED uczestnicy sprawnie wymieniają się informacjami, a rozbieżności w danych zostały praktycznie wyeliminowane. Dzięki IBM i jego partnerom kupujący samochody otrzymali potwierdzenie spełnienia regulacji środowiskowych i bezpieczeństwa, zaś instytucje zyskały dostęp do transparentnych, aktualnych i dokładnych danych dot. zgodności produkcji z obowiązującym prawem. Gorąco zachęcam do zapoznania się z ofertą IBM Blockchain dostępną na stronie https://www.ibm.com/blockchain/getting-started oraz pozostałymi przypadkami użycia blockchaina przez IBM dostępnymi pod linkiem https://www.ibm.com/blockchain/use-cases/.
